---
title: "Estimating Access to Rabies Post-Exposure Prophylaxis in Madagascar"
author: ""
date: 
output:
  word_document:
    reference_docx: format_docs/word_styles_reference_01.docx
  pdf_document:
    includes:
      in_header: mystyle.sty
  html_document: default
css: style.css
---

```{r directory, echo=FALSE, message = FALSE, results = 'hide'}
rm(list = ls())
require("knitr")
knitr::opts_chunk$set(fig.pos = 'h')
```

## INTRODUCTION

[Start broadly with inequity?]
To cite = Jess’s, Alegana, Emily from JHU.
Inequities in access to healthcare and interventions are a major driver of the burden of disease in human populations. These inequities can be driven by socioeconomics, lack of awareness and education, and by geographic accessibility. Despite the impact of access in shaping burden, incorporating these factors into estimations of burden is challenging due to limited data and lack of representation in data of the most marginalized groups (i.e. remote or low income populations). 

  
<br>

Human rabies post-exposure prophylaxis prevents fatalities if delivered in a timely manner, however, access to this intervention is highly limited in areas where the disease is endemic. Canine rabies causes an estimated 59,000 human deaths annually that could be prevented by PEP. 
  
<br>

The majority of studies which estimate burden of rabies use probability decision tree frameworks, often with the key assumptions that overall reported bite incidence (i.e. both bites due to non-rabid and rabid animals) are proportional to rabies incidence and that reporting is uniform across space. However, these estimations… Given little data on true exposures of rabies how do we do this? Newly developed frameworks which rely on in-country data on key parameters likely better capture burden by disentangling rabid from non-rabid bites and generating incidence from estimates of the dog population and control in the dog population. 

<br>

Here we extend this framework to include spatial access to PEP, using bite patient data from 27 clinics in Madagascar, a rabies endemic country with a largely absent control program in the canine population. Institut Pasteur de Madagascar (IPM) provides PEP at no-cost to the government or to the patients at 31 clinics across the country. PEP is not available at any other public clinics or through the private sector. Given that rabies is endemic in the country and there is effectively no vaccination of domestic dogs, we use predictions of incidence from dynamic models and 
We flip the standard decision tree and make the assumption that reported bite incidence reflects access and reporting to PEP rather than differences in rabies incidence.

## METHODS

### Bite patient data
We used the database of bite patient forms submitted from 27 ARMC between 2011-2014. These were paper forms that were sent to IPM as frequently as monthly to annually by individual clinics. Two clinics, the IPM ARMC and the Fianarantsoa ARMC used computer databases from which the data during this period were extracted and merged to the larger database. These data include details on the location of the bite patient and biting animal (*cite baseline data paper*). We also had the number of doses delivered on an annual basis to each clinic and used this information to estimate submission rates of paper forms to IPM for each clinic as described in (*Moramanga paper + baseline data paper*, using minimum # of doses expected based on clinic throughput). As there were many discrepancies between commune names in the GIS administrative layer and the names written on the forms, we used fuzzy matching to find the closest matching commune names and manually checked these.

RIG data?

<br>

### GIS Data
We use the global friction surface for 2015 generated by the Malaria Atlas Project ( https://map.ox.ac.uk/research-project/accessibility_to_cities/, Weiss et al. 2015,) and GPS points of clinics to get travel time to the nearest ARMC for the country of Madagascar at a 1 x 1 km scale. We then averaged these to the commune level, using administrative shapefiles available trhough the UN Office for the Coordination of Humanitarian Affairs. For each clinic, we defined the catchment area as all communes for which the clinic was the closest ARMC. Population estimates were taken from the 2015 UN adjusted population projections from World Pop (www.worldpop.org, Linaird et al. 2012) and also aggreagated to the commune level. 

<br>

### Model of reporting as a function of travel time
We model the bites reported annually to the clinic ($B_{i,t}$) for each commune using a Bayesian state-space framework as follows:
  
$$ B_{i,t} =  k_{c,t} \times \rho_i \times(R_{i,t} + N_{i,t}) $$
  
$k_{c,t}$ is the annual reporting at the catchment level (the product of the estimated proportion of forms that were submitted and the proportion of patients for which we were able to match commune names for that year).
  
$p_i$ is the reporting of all bites which follows the logistic function:
  
$$ \rho_{i} = \frac{C}{1 + e^{\frac{A - x}{d}}}$$
  
where $C$ is a limiting function on the y-axis that measures probability of attendance when distance is zero, $X$ is the log transformed travel times in minutes, $d$ is the distance decay parameter, and A is an asymptote factor at an inflection point of the model. We fix C to 0.90 (estimated from the Moramanga data), as even at minimal travel times, there are people that do not report bites for other reasons than accessibility. 
  
<br>

$N_{i,t}$ is the non-rabid bite incidence as a function of human population size **(Need to think about how to justify this...)**.
    
<br>

$$ N_{i,t} = Poisson(\beta_pP_i)$$
    
<br>

$R_{i,t}$ is drawn from a uniform distribution between the minimum and maximum expected number of human exposures. We calculate this as:
    
<br>

$$r \times D \times p_{exp}$$ 
    
<br>

where $r$ is rabies incidence in dogs in the absence of any vaccination multiplied by the estimated dog population in the commune ($D_i$) and the exposure rate per rabid dogs ($p_{exp}$ = 0.39 persons exposed per rabid dog)(Hampson et al. 2018). We estimate the dog population by using a human:dog ratio of 5 to generate our maximum expected incidence and an HDR of 25 for our minimum expected incidence. As there is little data on dog populations in Madagascar, this range of HDRs encompasses a wide range of HDRs observed across Africa(cite?). 
  
<br>

We use RJAGS (...) to fit this model to our reported bites at the commune level over the 4-year period using non-informative priors for $A$ $d$ and $\beta_p$

<br>

### Model evaluation and prediction
We fitted the model to data from n catchments which had above x% clinic level reporting {$k_c$} for all four years.

We used 

For three other catchments with reporting above x% we used to out-of-fit predict...
Ability to predict average annual/monthly bite incidence by travel time
Ability to predict out-of-fit to other catchments 
(observed to expected mean incidence over 4 year period (monthly or annual)

<br>

### Sensitivity analyses
Sensitivity to R (@ what level of human exposure incidence!)
Simulate and recover params? @ what *true* incidence does p_i become non-identifiable...

<br>

### Exploring alternative scenarios and estimation of burden
We estimate burden of human rabies deaths as follows:

$$ D_i = p_{death}\times (1-\rho_i) \times R_i $$
where $p_{death}$ is the probability of death given an exposure in the absence of PEP, $\rho_i$ is the estimated commune specific reporting probability derived from the model, and $R_i$ is the expected rabies incidence. **We use Monte Carlo? simulation drawing from a dist of incidence to get an average number of expected deaths.** We do not include potential deaths due to imperfect PEP (i.e. not completing at least 3 doses), delays in adminsitration, or lack of RIG.

We consider three scenarios:
1. The baseline with the current clinic locations (n = 31)
2. Expansion of ARMC to one clinic per district (n = 114)
3. Expansion of ARMC to all CSB IIs (n = ...?)

We use data on the location of **CSBs** provided by IPM to regenerate travel times to the nearest ARMC given expansion as per scenario 2 and 3. We then predict the expected reporting rate from the model given these new travel times and compare the relative decreases in burden for the three scenarios.

<br>




