#!/bin/bash
#SBATCH --ntasks=101
#SBATCH --cpus-per-task=1
#SBATCH -J  incremental
#SBATCH -t 48:00:00
# sends mail when process begins, and
# when it ends
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=mrajeev@princeton.edu

export OMPI_MCA_btl="tcp,self,sm"
module load openmpi/gcc/2.0.2
srun Rscript ./R/scenario_incremental.R
