#!/bin/bash
#SBATCH --ntasks=31
#SBATCH --cpus-per-task=1
#SBATCH -J  catchments
#SBATCH -t 24:00:00
# sends mail when process begins, and
# when it ends
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=mrajeev@princeton.edu

export OMPI_MCA_btl="tcp,self,sm"
module load openmpi/gcc/2.0.2
srun Rscript ./R/extract_to_commune.R
