#!/bin/bash
#SBATCH -N 1 # node count
#SBATCH --ntasks-per-node=20
#SBATCH -J  aggPop
#SBATCH --mem-per-cpu=8000
#SBATCH -t 12:00:00
# sends mail when process begins, and
# when it ends
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=mrajeev@princeton.edu

Rscript ./R/01_gis/02_aggregate_WP.R 20
