#!/bin/bash
#SBATCH -N 1 # node count
#SBATCH --ntasks-per-node=10
#SBATCH --mem-per-cpu=7000
#SBATCH -J candidates
#SBATCH -t 12:00:00
# sends mail when process begins, and
# when it ends
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=mrajeev@princeton.edu

Rscript ./R/04_addclinics/01_ttimes_candidates.R 10
