#!/bin/bash
#SBATCH -N 1 # node count
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=25000
#SBATCH -J  pop2pix
#SBATCH -t 12:00:00
# sends mail when process begins, and
# when it ends
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=mrajeev@princeton.edu

Rscript ./R/01_gis/pop_to_pix.R
