#!/bin/bash
#SBATCH --ntasks=50
#SBATCH --cpus-per-task=1
#SBATCH -J  vials
#SBATCH -t 12:00:00
# sends mail when process begins, and
# when it ends
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=mrajeev@princeton.edu

export OMPI_MCA_btl="tcp,self,sm"
module load openmpi/gcc/2.0.2
srun Rscript ./R/05_predictions/02_vials_incremental.R
