#!/bin/bash
#SBATCH -N 1 # node count
#SBATCH --ntasks-per-node=18
#SBATCH -J scenario_alt
#SBATCH -t 12:00:00
# sends mail when process begins, and
# when it ends
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=mrajeev@princeton.edu

Rscript ./R/test_scenario.R 18
