---
title: ""
author: ""
date: "10/2/2020"
output: 
  pdf_document:
    keep_tex: false
---

Dear Editor, 

We are submitting our manuscript entitled “How geographic access to care shapes disease burden: the current impact of post-exposure prophylaxis and potential for expanded access to prevent human rabies deaths in Madagascar” for consideration for publication in PLoS Neglected Tropical Disease. Our article presents a modeling framework to estimate how geographic access to post-exposure prophylaxis (PEP) shapes the burden of human rabies deaths. 

We use data from clinics across Madagascar and at multiple scales and travel time estimates to clinics provisioning PEP to fit models of reported bite incidence. We then use the predictions these models and integrate them into a decision tree framework to extrapolate rabies burden and vial demand. Finally, we examine how expanding access strategically can reduce human rabies burden. This work is inline with a body of work that shows the impacts of geography on access to care and disease outcomes. It also provides a modeling framework that could be usefully applied to other countries where PEP access is currently geographically restricted in how to effectively increase expansion, particularly in light of the recent addition of human rabies vaccine to the Gavi investment portfolio. 

We thank you for your consideration.  

Sincerely,  
Malavika Rajeev, Princeton University
